💥Improve invites
NAFTeam/NAFF pull request #209
Opened 2022-01-21 19:14 UTC by leestarb

## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition

## Description

Awesome improvements for the `Invite` object

## Changes

- Add delete ability
- Fix invite's users properties 💥
- Implement `__str__` and `__repr__`

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

2022-01-21 20:54 UTC, Wolfhound905 requested changes

2022-01-21 20:54 UTC, Wolfhound905 commented on dis_snek/api/http/http_requests/invites.py
> +class InviteRequests:
This file is never used, and you never added it to 
https://github.com/Discord-Snake-Pit/Dis-Snek/blob/e85c04abf42650958a2a750674650cccbc6456f1/dis_snek/api/http/http_client.py#L52

2022-01-21 20:54 UTC, Wolfhound905 commented on dis_snek/api/http/http_requests/invites.py
> +    async def delete_invite(self, invite_code: str, reason: Absent[str] = MISSING) -> dict:
This is a duplicate of a function we already have in https://github.com/Discord-Snake-Pit/Dis-Snek/blob/e85c04abf42650958a2a750674650cccbc6456f1/dis_snek/api/http/http_requests/channels.py#L241
I do not think this file is needed.

2022-01-22 02:06 UTC, benwoo1110 commented on dis_snek/models/discord/invite.py
>      created_at: Timestamp = field(default=MISSING, converter=optional_c(optional_timestamp_converter))
I think this can be included in repr too?

2022-01-22 08:16 UTC, benwoo1110 approved these changes

2022-01-22 08:30 UTC, leestarb commented
Please look at https://discord.com/channels/870046872864165888/870046872864165893/934362064737140796

2022-01-23 07:04 UTC, LordOfPolls approved these changes

2022-01-23 07:06 UTC, merged