feat: Add get util
NAFTeam/NAFF pull request #243
Opened 2022-02-03 04:58 UTC by zevaryx

## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

Discord.py had 2 utilities for searching an iterable, `find` and `get`. Dis-Snek already implements `find`, but is missing an implementation for `get`. This PR adds that missing implementation.

## Changes

- Add `dis_snek.client.misc_utils.get`

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

2022-02-03 05:25 UTC, silasary approved these changes

2022-02-03 06:42 UTC, leestarb commented
- [x] Looks good

2022-02-03 06:42 UTC, leestarb approved these changes

2022-02-04 09:38 UTC, benwoo1110 approved these changes
looks good, maybe we should have a `get_all` or similar where it returns all elements that matches, not just the first one.

2022-02-04 15:48 UTC, zevaryx commented
Honestly not a bad idea. Want me to add a get_all and find_all to this PR?

2022-02-04 16:02 UTC, silasary commented
That would be great

2022-02-04 18:53 UTC, leestarb requested changes
For speedup purposes, please use the list literal instead of the function (C408)

2022-02-04 19:08 UTC, zevaryx commented
> For speedup purposes, please use the list literal instead of the function (C408)

Changed

2022-02-05 17:49 UTC, LordOfPolls approved these changes

2022-02-05 17:50 UTC, LordOfPolls commented
Pending re-review from @leestarb

2022-02-05 17:52 UTC, leestarb approved these changes
Ok, but

2022-02-05 17:52 UTC, leestarb commented on dis_snek/client/utils/misc_utils.py
> +    return matches
You could rewrite this as list comprehension in a line.

2022-02-05 18:17 UTC, leestarb commented on dis_snek/client/utils/misc_utils.py
> +    return matches
```suggestion
return [el for el in sequence if predicate(el)]
```

2022-02-05 20:00 UTC, zevaryx commented on dis_snek/client/utils/misc_utils.py
> +    return matches
Changed in latest push

2022-02-06 04:13 UTC, benwoo1110 approved these changes

2022-02-06 04:21 UTC, leestarb approved these changes

2022-02-07 07:12 UTC, merged