DOCS: add modal and attachment option docs, and refactor some docs
NAFTeam/NAFF pull request #267
Opened 2022-02-09 07:50 UTC by Kigstn

## What type of pull request is this?

- [ ] Non-breaking code change
- [ ] Breaking code change
- [x] Documentation change/addition

## Description

This adds docs for modals and attachment option and reactors some outdated info

## Changes

- add modal guide
- add attachment option to command guide
- change `target_id` to `target` in context menu guide
- add additional `@listen()` styles to event docs
- update the guide indexing. this should help prevent that in the future

## Checklist

- [ ] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [ ] I've ensured my code works on `Python 3.10.x`
- [ ] I've tested my code

2022-02-09 07:51 UTC, Kigstn commented
Note: This depends on pr #265 and #186

2022-02-09 08:11 UTC, LordOfPolls commented
![image](https://user-images.githubusercontent.com/22540825/153152946-d220d6f5-ca31-48ca-81ce-5eaa96334044.png)
Suggest using newer screenshots, this bug with modals has been fixed

2022-02-09 09:46 UTC, leestarb requested changes

2022-02-09 09:46 UTC, leestarb commented on docs/src/Guides/01 Getting Started.md
> +For more examples, check out the [examples page](/Guides/90 Example)
The examples url is now invalid
```suggestion
For more examples, check out the [examples page](/Guides/99 Example)
```

2022-02-09 09:56 UTC, Kigstn commented on docs/src/Guides/01 Getting Started.md
> +For more examples, check out the [examples page](/Guides/90 Example)
Good catch, forgot to rename that

2022-02-09 13:10 UTC, leestarb commented on docs/src/Guides/01 Getting Started.md
> +For more examples, check out the [examples page](/Guides/90 Example)
Why did you rename it?

2022-02-09 13:11 UTC, leestarb approved these changes
Looks good

2022-02-10 15:33 UTC, silasary approved these changes

2022-02-11 07:44 UTC, merged