fix: Use correct fetch methods in `fetch_all_threads`
NAFTeam/NAFF pull request #300
Opened 2022-02-20 14:26 UTC by benwoo1110

## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition

## Description

Probably an oversight when methods were renamed.

## Changes

* Fixed the wrong fetch methods used

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [ ] I've tested my code

2022-02-20 16:42 UTC, leestarb requested changes

2022-02-20 16:42 UTC, leestarb commented on dis_snek/models/discord/channel.py
> +        archived_threads = await self.fetch_active_threads()
__Archived__

2022-02-21 03:37 UTC, benwoo1110 commented on dis_snek/models/discord/channel.py
> +        archived_threads = await self.fetch_active_threads()
nothing happened there

2022-02-21 04:14 UTC, leestarb approved these changes

2022-02-21 07:53 UTC, merged