feat: Send error to channel with default error handlers
NAFTeam/NAFF pull request #427
Opened 2022-04-06 10:38 UTC by LordOfPolls

## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

The default error handler now sends the error to the channel the command was ran in

## Changes

- Added send call to error handler
- Organised imports and converted relative imports 

## Checklist

- [ ] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [ ] I've ensured my code works on `Python 3.10.x`
- [ ] I've tested my code

2022-04-06 10:48 UTC, LordOfPolls commented
![image](https://user-images.githubusercontent.com/22540825/161958474-773bc2cd-c2d8-443e-a0c2-a95c3900e3c6.png)

2022-04-06 10:50 UTC, Astrea49 commented
Couldn't this have potentially dangerous information, like bot tokens or API keys? I think it's a bit unwise to show off the full traceback.

2022-04-06 10:55 UTC, LordOfPolls commented
Let them leak dammit \s 

Jokes aside, the trace back will leak the token/api key *if* the user was daft enough to hardcode their token/keys in their src files. *Not* showing tracebacks limits the amount of usable information that can be gleamed from the error message. Bot developers could implement their own error messages that allow for looking up errors, but the base lib cant have that functionality. 

I do honestly think that vulnerability is something the bot developer should mitigate, not us. I'd also be inclined to point out other libraries send tracebacks by default too

2022-04-06 11:03 UTC, LordOfPolls commented
As the bare-minimum ill filter the bot token. I will make it clear to those reading this 

**DO NOT RELY ON THIS TO KEEP YOUR TOKENS SAFE**
Do the bare minimum security on your projects and put the token in a text file or something

2022-04-06 19:00 UTC, leestarb commented
I suggest moving this to the debug scale
+
I dont think this is really useful

2022-04-06 19:02 UTC, leestarb requested changes

2022-04-06 19:02 UTC, leestarb commented on dis_snek/client/client.py
> +            out = "".join(traceback.format_exception(error))
This needs the [:2000] slice ig

2022-04-06 19:39 UTC, LordOfPolls commented
> I suggest moving this to the debug scale + I dont think this is really useful

I disagree on both counts

2022-04-06 19:39 UTC, LordOfPolls commented on dis_snek/client/client.py
> +            out = "".join(traceback.format_exception(error))
Agreed, adding now

2022-04-07 08:37 UTC, LordOfPolls commented
![image](https://user-images.githubusercontent.com/22540825/162157474-28bf1b62-c867-4f4d-a468-0b13815d90dc.png)

2022-04-08 06:34 UTC, LordOfPolls commented
Requesting reviews

2022-04-08 13:41 UTC, leestarb commented
I suggest moving this logic to the utils package

2022-04-08 19:52 UTC, LordOfPolls commented
Moving which logic? The logic for the 3 different embeds? 

Is that really utility worthy? It's 3 if statements and some embeds. Surely if youre implimenting your own error handler you'd want to create your own embeds, which would defeat the point of making the logic a util

2022-04-12 01:27 UTC, silasary approved these changes

2022-04-12 18:44 UTC, merged