Feat: Intent warning for events and prefixed commands
NAFTeam/NAFF pull request #577
Opened 2022-07-31 10:26 UTC by Kigstn

## What type of pull request is this?

- [x] Non-breaking code change
- [ ] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

This warns users if they use a gateway event / prefixed commands and do not have the required intents enabled. If users read their console output, this should make debugging easier for them.

Lists of intents and events taken from https://discord.com/developers/docs/topics/gateway#list-of-intents

## Changes

- warn when event is missing required intent
- warn when prefixed commands are used but the message content intent is missing

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

2022-07-31 10:44 UTC, LordOfPolls commented
I'd suggest using references to the event objects rather than strings. That way if we were to refactor they'd be caught by most modern IDEs

2022-07-31 12:42 UTC, Kigstn commented
> I'd suggest using references to the event objects rather than strings. That way if we were to refactor they'd be caught by most modern IDEs

Sure, good call

2022-07-31 14:16 UTC, Astrea49 commented
Too lazy to do a proper review, but it should be noted that prefixed commands will work fine even without the message content intent *unless* they change the prefixes used to outside of their defaults (you can always mention the bot). Probably worth checking for that.

2022-08-02 08:58 UTC, silasary requested changes

2022-08-02 08:58 UTC, silasary commented on naff/client/client.py
> +from naff.api.events import (
We are already importing the events namespace on line 34, let's just use that, and refer to events as `events.Whatever`, the same way we do when dispatching them.

2022-08-02 12:10 UTC, silasary approved these changes

2022-08-02 12:14 UTC, silasary commented on naff/client/client.py
> +from naff.api.events import MessageCreate, RawGatewayEvent, processors, Component, BaseEvent
Bonus points if you refactor all existing references to these to also use `events.`, but I'm happy to merge without that

2022-08-02 12:37 UTC, merged