The kwargening
NAFTeam/NAFF pull request #697
Opened 2022-10-25 16:34 UTC by LordOfPolls

## What type of pull request is this?

- [ ] Non-breaking code change
- [x] Breaking code change
- [ ] Documentation change/addition
- [ ] Tests change

## Description

Makes all edit and send methods use kwargs for *most*™️ parameters 

## Changes

As above

## Checklist

- [x] I've formatted my code with [Black](https://black.readthedocs.io/en/stable/)
- [x] I've ensured my code works on `Python 3.10.x`
- [x] I've tested my code

2022-10-25 19:59 UTC, AlbertUnruh requested changes
Correct me if I'm wrong, but you missed these:

https://github.com/NAFTeam/NAFF/blob/65538ea52db4aaa369adfba1daef069192e874f0/naff/models/naff/context.py#L526-L543
https://github.com/NAFTeam/NAFF/blob/65538ea52db4aaa369adfba1daef069192e874f0/naff/models/discord/webhooks.py#L251-L266

2022-10-26 01:44 UTC, silasary commented
This might be the most breaking change of 2.x so far :O

2022-10-26 03:33 UTC, LordOfPolls commented
> Correct me if I'm wrong, but you missed these:
> 
> https://github.com/NAFTeam/NAFF/blob/65538ea52db4aaa369adfba1daef069192e874f0/naff/models/naff/context.py#L526-L543
> 
> https://github.com/NAFTeam/NAFF/blob/65538ea52db4aaa369adfba1daef069192e874f0/naff/models/discord/webhooks.py#L251-L266

You'd be right, I didn't consider those two - I'll amend them shortly

2022-10-26 07:39 UTC, AlbertUnruh approved these changes

2022-10-27 04:14 UTC, silasary approved these changes

2022-10-27 17:54 UTC, merged